name = "battery_name"
b_min_caps = "min_energy_capacities"
b_max_caps = "max_energy_capacities"
b_max_powers = "max_powers"
b_effs = "efficiencies"
b_init_energy = "init_energy_levels"
b_eod_energy = "end_of_day_energy_levels"
b_charges = "charges"
b_discharges = "discharges"
b_agg_demands = "aggregate_powers"
b_soc = "socs"
b_num_batteries = "num_batteries"

d_datetime = "timestamp"
d_demand = "demand"
d_actual_demand_original = "actual_original"
d_actual_demand_modified = "actual_modified"
d_actual_max_demand_original = "actual_max_original"
d_actual_max_demand_modified = "actual_max_modified"
d_forecast_demand_original = "forecast_original"
d_forecast_demand_optimised = "forecast_optimised"
d_forecast_max_demand_original = "forecast_max_original"
d_forecast_max_demand_optimised = "forecast_max_optimised"

r_annual_max = "annual_charge"
r_summer_max = "summer_charge"
r_peak_demand_charge = "peak_demand_charge"
r_months = "months"
r_demand_threshold = "threshold"
r_charge_name = "charge_name"
r_cycle_start_month = "begin_cycle_month"

status_updated = "threshold_updated"
status_unchanged = "threshold_unchanged"
status_none = "threshold_none"

l_frits_historical = "frits_historical"
l_frits_forecast = "frits_forecast"
