This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./document.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file document.acn....done (54 entries accepted, 0 rejected).
Sorting entries....done (333 comparisons).
Generating output file document.acr....done (35 lines written, 0 warnings).
Output written in document.acr.
Transcript written in document.alg.
